import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import About from "./components/About";
import Contact from "./components/Contact";
import Hero from "./components/Hero";
import Navbar from "./components/Navbar";
import Projects from "./components/Projects";
import Work from "./components/Work";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='text-xl bg-slate-800 text-slate-100 text-center'>Hello World</div>

    </div>
  )
}
