import Head from 'next/head'
import About from '../components/About';
import Hero from '../components/Hero';
import Navbar from "../components/Navbar";
import Projects from '../components/Projects';
import Skills from '../components/Skills';
import Contact from '../components/Contact';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar />
    <Hero />
    <About />
    <Skills />
    <Projects />
    <Contact />
    </div>
  )
}
